version: '3.9'

services:
  pagedb:
    container_name: pagedb
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - pagedb:/var/lib/mysql
    networks:
      pagenet:
        aliases:
          - ${MYSQL_HOST}
    restart: always
    healthcheck:
      test: 'mysqladmin ping --silent'
      timeout: 1s
      retries: 100

  front:
    container_name: front
    build:
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '3000:80'
    networks:
      - pagenet
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    restart: always
    depends_on:
      pagedb:
        condition: service_healthy

volumes:
  pagedb:

networks:
  pagenet:
    name: pagenet
